#!/usr/bin/ruby


def fix_copyright(dir) 
    year = Time.now.year
    Dir.chdir(dir) do 
        Dir.glob('*.cpp').each do |file|
            puts file
            text = File.read(file)
            File.open(file, "w") do |file| 
                file.write(text.gsub!(/\(c\) \d\d\d\d/, "(c) #{year}"))
            end
        end
    end
end

fix_copyright 'compiler'
fix_copyright 'drivers'
