#!/usr/bin/python
# This script uploads a new release to the downloads section of the GitHub
# repository for the Jogo project.  Argument = version #

from boto.s3.connection import S3Connection
from boto.s3.key import Key
import sys
import os

HOME = os.path.expanduser('~')
VERSION = sys.argv[1]
AWS_ACCESS_KEY_FILE = os.path.join(HOME, '.awsaccesskey')
AWS_SECRET_KEY_FILE = os.path.join(HOME, '.awssecretkey')
try:
    AWS_ACCESS_KEY = open(AWS_ACCESS_KEY_FILE).read()
except:
    AWS_ACCESS_KEY = raw_input('AWS Access Key ID: ')
    fd = open(AWS_ACCESS_KEY_FILE, 'w')
    fd.write(AWS_ACCESS_KEY)
    fd.close()
try:
    AWS_SECRET_KEY = open(AWS_SECRET_KEY_FILE).read()
except:
    AWS_SECRET_KEY = raw_input('AWS Secret Key: ')
    fd = open(AWS_SECRET_KEY_FILE, 'w')
    fd.write(AWS_SECRET_KEY)
    fd.close()


if 'win32' in sys.platform:
    pkg = 'jogo-'+VERSION+'.exe'
    system = 'Windows'
elif 'darwin' in sys.platform:
    pkg = 'jogo-'+VERSION+'.pkg'
    system = 'OS X'
elif 'linux' in sys.platform:
    pkg = 'jogo-'+VERSION+'.deb'
    system = 'Linux'

# Generate the message body
print('Uploading file')


conn = S3Connection(AWS_ACCESS_KEY, AWS_SECRET_KEY)
bucket = conn.create_bucket('jogo-downloads')

key = Key(bucket)
key.key = pkg
key.set_contents_from_filename(pkg)
key.set_acl('public-read')
