#!/usr/bin/python

import re
import glob
import optparse
import subprocess

FILES = glob.glob("compiler/*.*") + glob.glob("tests/*.*")

parser = optparse.OptionParser(usage="%prog ORIG REPLACEMENT")
(options, args) = parser.parse_args()

if len(args) != 2:
    parser.error("invalid number of arguments")
    sys.exit(1)

RE = re.compile(r'\b%s\b' % args[0])
REPLACEMENT = args[1]
HPP = re.compile(r'\b%s.cpp$' % args[0])
CPP = re.compile(r'\b%s.hpp$' % args[0])

for fn in FILES:
    fd = open(fn, 'r')
    text = fd.read()
    fd.close()
    text = RE.sub(REPLACEMENT, text)
    fd = open(fn, 'w')
    fd.write(text)
    fd.close()
    if HPP.search(fn) or CPP.search(fn):
        dest = RE.sub(REPLACEMENT, fn)
        subprocess.check_call(['git', 'mv', fn, dest]) 
