#!/usr/bin/python

import os, sys, sets, shutil

def mkdir_p(path):
    # Make a directory, and ignore the error if the directory already exists.
    try:
        os.makedirs(path)
    except OSError:
        pass


def setup_vim():
    # Write default VIM options to the .vimrc file.  Be sure to preserve any
    # existing options, and remove duplicates.
    home = os.environ['HOME']
    options = sets.Set()
    try:
        for line in open(os.path.join(home, '.vimrc')):
            options.add(line.strip())
    except IOError:
        pass

    options.add('au BufNew,BufRead *.ll setf lex')
    options.add('set ruler')
    options.add('syntax on')
    options.add('set tabstop=4')
    options.add('set expandtab')
    options.add('colors molokai')
    options.add('set noerrorbells')
    options.add('set number')
    options.add('set nowrap')
    options.add('set t_Co=256')
    options.add('set guioptions-=m')
    options.add('set guioptions-=r')
    options.add('set guioptions-=T')

    with open(os.path.join(home, '.vimrc'), 'w') as f:
        f.write('\n'.join(options))

    # Write the other vim files (syntax, colors, etc).
    vimhome = ''
    if sys.platform == 'win32':
        vimhome = os.path.join(home, 'vimfiles')
    else:
        vimhome = os.path.join(home, '.vim')
    
    # Copy the vim syntax file
    mkdir_p(os.path.join(vimhome, 'syntax'))
    shutil.copy(
        os.path.join('scripts', 'jogo.vim'),
        os.path.join(vimhome, 'syntax', 'jogo.vim'))

    # Copy the ftdetect file
    mkdir_p(os.path.join(vimhome, 'ftdetect'))
    shutil.copy(
        os.path.join('scripts', 'ftdetect.vim'),
        os.path.join(vimhome, 'ftdetect', 'jogo.vim'))

    # Copy the colors file
    mkdir_p(os.path.join(vimhome, 'colors'))
    shutil.copy(
        os.path.join('scripts', 'molokai.vim'),
        os.path.join(vimhome, 'colors'))
    shutil.copy(
        os.path.join('scripts', 'earendel.vim'),    
        os.path.join(vimhome, 'colors'))

def setup_deps():
    # Install all dependencies needed for development
    print('Installing dependencies')
    if os.system('which apt-get') == 0:
        os.system('sudo apt-get install scons valgrind vim nasm g++')
        os.system('sudo easy_install boto')
    elif os.system('which yum') == 0:
        os.system('sudo yum install scons valgrind vim nasm g++')
        os.system('sudo easy_install boto')
    elif os.system('which brew') == 0:
        os.system('brew install scons')
        os.system('brew install nasm')
        os.system('sudo easy_install boto')
    else:
        print('Package manager not supported.')


setup_vim()
setup_deps()
