#!/usr/bin/ruby

require 'fileutils'
require 'set'
require 'rbconfig'

def setup_vim()
    home = ENV['HOME']
    options = Set.new
    FileUtils.touch(File.join(home, ".vimrc"))
    File.open(File.join(home, ".vimrc")).each_line do |line|
        options.add(line.strip)
    end

    options.add "au BufNew,BufRead *.ll setf lex"
    options.add "syntax on"
    options.add "set tabstop=4"
    options.add "set expandtab"
    options.add "colors molokai"
    options.add "set noerrorbells"
    options.add "set number"
    options.add "set nowrap"
    options.add "set t_Co=256"

    File.open(File.join(home, ".vimrc"), "w") do |file|
        options.each do |option|
            file.puts option
        end
    end

    vimhome = home
    if ENV['OS'] == 'Windows_NT'
        vimhome = File.join(vimhome, "vimfiles")
    else
        vimhome = File.join(vimhome, ".vim")
    end

    begin
        FileUtils.rm File.join(vimhome, "syntax", "apollo.vim")
    rescue
    end
    FileUtils.mkdir_p File.join(vimhome, "syntax")
    FileUtils.cp(
        File.join("scripts", "apollo.vim"), 
        File.join(vimhome, "syntax"))

    begin
        FileUtils.rm File.join(vimhome, "ftdetect", "apollo.vim")
    rescue
    end
    FileUtils.mkdir_p File.join(vimhome, "ftdetect")
    FileUtils.cp(
        File.join("scripts", "ftdetect.vim"),
        File.join(vimhome, "ftdetect", "apollo.vim"))

    FileUtils.mkdir_p File.join(vimhome, "colors")
    FileUtils.cp(
        File.join("scripts", "molokai.vim"), 
        File.join(vimhome, "colors"))
    FileUtils.cp(
        File.join("scripts", "earendel.vim"),
        File.join(vimhome, "colors"))
end

def setup_deps()

    puts "Installing dependencies"
    if system 'which apt-get'
        `sudo apt-get install scons valgrind vim nasm` 
    elsif system 'which yum'
        `sudo yum install scons valgrind vim nasm`
    elsif system 'which brew'
        `brew install scons`
        `brew install nasm`
        #`brew install valgrind` # Not supported yet
    else
        puts "Package manager not supported." 
    end
end

setup_vim
setup_deps
