#!/usr/bin/ruby

require 'fileutils'
require 'set'

def setup_vim()
    options = Set.new
    File.open("#{ENV['HOME']}/.vimrc").each_line do |line|
        options.add(line.strip)
    end

    options.add "au BufNew,BufRead *.ap setf apollo"
    options.add "syntax on"
    options.add "set tabstop=4"
    options.add "set expandtab"
    #options.add "colors molokai"
    #options.add "set noerrorbells"
    #options.add "set number"
    #options.add "set nowrap"
    #options.add "set t_Co=256"

    File.open("#{ENV['HOME']}/.vimrc", "w") do |file|
        options.each do |option|
            file.puts option
        end
    end

    FileUtils.rm "#{ENV['HOME']}/.vim/syntax/apollo.vim"
    FileUtils.mkdir_p "#{ENV['HOME']}/.vim/syntax/"
    FileUtils.ln "scripts/apollo.vim", "#{ENV['HOME']}/.vim/syntax/" 

    #FileUtils.mkdir_p "#{ENV['HOME']}/.vim/colors/"
    #FileUtils.cp "scripts/molokai.vim", "#{ENV['HOME']}/.vim/colors/"
end

def setup_deps()

    puts "Installing dependencies"
    if system 'which apt-get'
        `sudo apt-get install bison flex scons ruby valgrind` 
    elsif system 'which yum'
        `sudo yum install bison flex scons ruby valgrind`
    else
        puts "Package manager not supported." 
    end
end

setup_vim
setup_deps()
