#!/usr/bin/ruby

require 'optparse'

failed = false
options = {}

OptionParser.new do |opts|
    opts.on('-f', '--full', 'Run all tests, including memchecker') do |v|
        options[:full] = v
    end
    opts.on('-v', '--verbose', 'Print test status') do |v|
        options[:verbose] = v
    end
end.parse!

Dir.chdir('tests')

tests = Dir.glob('*.ap')
tests.each do |test|
    if options[:full]
        result = `valgrind --leak-check=full -q ../bin/test #{test} 2>&1 | diff - #{test}.out`
    else
        result = `../bin/test #{test} 2>&1 | diff - #{test}.out`
    end
    if !result.empty? || $? != 0
        (1..79).each { putc '-' }        
        puts
        puts "FAILED TEST: #{test}"
        (1..79).each { putc '-' }        
        puts
        puts result
        failed = true
    end
end



if failed 
    exit(-1)
elsif options[:verbose]
    puts "All #{tests.length} tests passed."
end



